INSERT INTO
    `accesslist` (`id`,`label`,`url`)
    VALUES
        (NULL,'Inventory','/inventory/inventories/admin');

INSERT INTO 
    `authitem` (`name`, `type`, `description`, `bizrule`, `data`)      
    VALUES 
        ('Inventory.Inventories.View', 0, NULL, NULL,'N;'),
        ('Inventory.Inventories.Create', 0, NULL, NULL,'N;'),
        ('Inventory.Inventories.Update', 0, NULL, NULL,'N;'),
        ('Inventory.Inventories.Delete', 0, NULL, NULL,'N;'),
        ('Inventory.Inventories.Admin', 0, NULL, NULL,'N;'),
        ('Inventory.Inventories.Index', 0, NULL, NULL,'N;'),
        ('Inventory.Inventories.InitialInventoryForm', 0, NULL, NULL,'N;'),
        
        ('Inventory.Stocks.View', 0, NULL, NULL,'N;'),
        ('Inventory.Stocks.Create', 0, NULL, NULL,'N;'),
        ('Inventory.Stocks.Update', 0, NULL, NULL,'N;'),
        ('Inventory.Stocks.Delete', 0, NULL, NULL,'N;'),
        ('Inventory.Stocks.Admin', 0, NULL, NULL,'N;'),
        ('Inventory.Stocks.Index', 0, NULL, NULL,'N;'),
        
        ('Inventory.Locations.View', 0, NULL, NULL,'N;'),
        ('Inventory.Locations.Create', 0, NULL, NULL,'N;'),
        ('Inventory.Locations.Update', 0, NULL, NULL,'N;'),
        ('Inventory.Locations.Delete', 0, NULL, NULL,'N;'),
        ('Inventory.Locations.Admin', 0, NULL, NULL,'N;'),
        ('Inventory.Locations.Index', 0, NULL, NULL,'N;'),
        
        ('Inventory.Suppliers.View', 0, NULL, NULL,'N;'),
        ('Inventory.Suppliers.Create', 0, NULL, NULL,'N;'),
        ('Inventory.Suppliers.Update', 0, NULL, NULL,'N;'),
        ('Inventory.Suppliers.Delete', 0, NULL, NULL,'N;'),
        ('Inventory.Suppliers.Admin', 0, NULL, NULL,'N;'),
        ('Inventory.Suppliers.Index', 0, NULL, NULL,'N;'),
        
        ('Inventory.Manufacturers.View', 0, NULL, NULL,'N;'),
        ('Inventory.Manufacturers.Create', 0, NULL, NULL,'N;'),
        ('Inventory.Manufacturers.Update', 0, NULL, NULL,'N;'),
        ('Inventory.Manufacturers.Delete', 0, NULL, NULL,'N;'),
        ('Inventory.Manufacturers.Admin', 0, NULL, NULL,'N;'),
        ('Inventory.Manufacturers.Index', 0, NULL, NULL,'N;'),
        
        ('Inventory.ContainerTypes.View', 0, NULL, NULL,'N;'),
        ('Inventory.ContainerTypes.Create', 0, NULL, NULL,'N;'),
        ('Inventory.ContainerTypes.Update', 0, NULL, NULL,'N;'),
        ('Inventory.ContainerTypes.Delete', 0, NULL, NULL,'N;'),
        ('Inventory.ContainerTypes.Admin', 0, NULL, NULL,'N;'),
        ('Inventory.ContainerTypes.Index', 0, NULL, NULL,'N;'),
        
        ('Inventory.UnitTypes.View', 0, NULL, NULL,'N;'),
        ('Inventory.UnitTypes.Create', 0, NULL, NULL,'N;'),
        ('Inventory.UnitTypes.Update', 0, NULL, NULL,'N;'),
        ('Inventory.UnitTypes.Delete', 0, NULL, NULL,'N;'),
        ('Inventory.UnitTypes.Admin', 0, NULL, NULL,'N;'),
        ('Inventory.UnitTypes.Index', 0, NULL, NULL,'N;');
        

INSERT INTO 
    `authitemchild` (`parent`, `child`)      
    VALUES 
        ('Lab - System Manager', 'Inventory.Inventories.View'),
        ('Lab - System Manager', 'Inventory.Inventories.Create'),
        ('Lab - System Manager', 'Inventory.Inventories.Update'),
        ('Lab - System Manager', 'Inventory.Inventories.Delete'),
        ('Lab - System Manager', 'Inventory.Inventories.Admin'),
        ('Lab - System Manager', 'Inventory.Inventories.Index'),
        ('Lab - System Manager', 'Inventory.Inventories.InitialInventoryForm'),
        ('Lab - User', 'Inventory.Inventories.View'),
        ('Lab - User', 'Inventory.Inventories.Create'),
        ('Lab - User', 'Inventory.Inventories.Update'),
        ('Lab - User', 'Inventory.Inventories.Delete'),
        ('Lab - User', 'Inventory.Inventories.Admin'),
        ('Lab - User', 'Inventory.Inventories.Index'),
        ('Lab - User', 'Inventory.Inventories.InitialInventoryForm'),
        
        ('Lab - System Manager', 'Inventory.Stocks.View'),
        ('Lab - System Manager', 'Inventory.Stocks.Create'),
        ('Lab - System Manager', 'Inventory.Stocks.Update'),
        ('Lab - System Manager', 'Inventory.Stocks.Delete'),
        ('Lab - System Manager', 'Inventory.Stocks.Admin'),
        ('Lab - System Manager', 'Inventory.Stocks.Index'),
        ('Lab - User', 'Inventory.Stocks.View'),
        ('Lab - User', 'Inventory.Stocks.Create'),
        ('Lab - User', 'Inventory.Stocks.Update'),
        ('Lab - User', 'Inventory.Stocks.Delete'),
        ('Lab - User', 'Inventory.Stocks.Admin'),
        ('Lab - User', 'Inventory.Stocks.Index'),
        
        ('Lab - System Manager', 'Inventory.Locations.View'),
        ('Lab - System Manager', 'Inventory.Locations.Create'),
        ('Lab - System Manager', 'Inventory.Locations.Update'),
        ('Lab - System Manager', 'Inventory.Locations.Delete'),
        ('Lab - System Manager', 'Inventory.Locations.Admin'),
        ('Lab - System Manager', 'Inventory.Locations.Index'),
        ('Lab - User', 'Inventory.Locations.View'),
        ('Lab - User', 'Inventory.Locations.Create'),
        ('Lab - User', 'Inventory.Locations.Update'),
        ('Lab - User', 'Inventory.Locations.Delete'),
        ('Lab - User', 'Inventory.Locations.Admin'),
        ('Lab - User', 'Inventory.Locations.Index'),
        
        ('Lab - System Manager', 'Inventory.Suppliers.View'),
        ('Lab - System Manager', 'Inventory.Suppliers.Create'),
        ('Lab - System Manager', 'Inventory.Suppliers.Update'),
        ('Lab - System Manager', 'Inventory.Suppliers.Delete'),
        ('Lab - System Manager', 'Inventory.Suppliers.Admin'),
        ('Lab - System Manager', 'Inventory.Suppliers.Index'),
        ('Lab - User', 'Inventory.Suppliers.View'),
        ('Lab - User', 'Inventory.Suppliers.Create'),
        ('Lab - User', 'Inventory.Suppliers.Update'),
        ('Lab - User', 'Inventory.Suppliers.Delete'),
        ('Lab - User', 'Inventory.Suppliers.Admin'),
        ('Lab - User', 'Inventory.Suppliers.Index'),
        
        ('Lab - System Manager', 'Inventory.Manufacturers.View'),
        ('Lab - System Manager', 'Inventory.Manufacturers.Create'),
        ('Lab - System Manager', 'Inventory.Manufacturers.Update'),
        ('Lab - System Manager', 'Inventory.Manufacturers.Delete'),
        ('Lab - System Manager', 'Inventory.Manufacturers.Admin'),
        ('Lab - System Manager', 'Inventory.Manufacturers.Index'),
        ('Lab - User', 'Inventory.Manufacturers.View'),
        ('Lab - User', 'Inventory.Manufacturers.Create'),
        ('Lab - User', 'Inventory.Manufacturers.Update'),
        ('Lab - User', 'Inventory.Manufacturers.Delete'),
        ('Lab - User', 'Inventory.Manufacturers.Admin'),
        ('Lab - User', 'Inventory.Manufacturers.Index'),
        
        ('Lab - System Manager', 'Inventory.ContainerTypes.View'),
        ('Lab - System Manager', 'Inventory.ContainerTypes.Create'),
        ('Lab - System Manager', 'Inventory.ContainerTypes.Update'),
        ('Lab - System Manager', 'Inventory.ContainerTypes.Delete'),
        ('Lab - System Manager', 'Inventory.ContainerTypes.Admin'),
        ('Lab - System Manager', 'Inventory.ContainerTypes.Index'),
        ('Lab - User', 'Inventory.ContainerTypes.View'),
        ('Lab - User', 'Inventory.ContainerTypes.Create'),
        ('Lab - User', 'Inventory.ContainerTypes.Update'),
        ('Lab - User', 'Inventory.ContainerTypes.Delete'),
        ('Lab - User', 'Inventory.ContainerTypes.Admin'),
        ('Lab - User', 'Inventory.ContainerTypes.Index'),
        
        ('Lab - System Manager', 'Inventory.UnitTypes.View'),
        ('Lab - System Manager', 'Inventory.UnitTypes.Create'),
        ('Lab - System Manager', 'Inventory.UnitTypes.Update'),
        ('Lab - System Manager', 'Inventory.UnitTypes.Delete'),
        ('Lab - System Manager', 'Inventory.UnitTypes.Admin'),
        ('Lab - System Manager', 'Inventory.UnitTypes.Index'),
        ('Lab - User', 'Inventory.UnitTypes.View'),
        ('Lab - User', 'Inventory.UnitTypes.Create'),
        ('Lab - User', 'Inventory.UnitTypes.Update'),
        ('Lab - User', 'Inventory.UnitTypes.Delete'),
        ('Lab - User', 'Inventory.UnitTypes.Admin'),
        ('Lab - User', 'Inventory.UnitTypes.Index');
        