INSERT INTO
    `accesslist` (`id`,`label`,`url`)
    VALUES
        (NULL,'Equipment','/equipment/equipment/admin');

INSERT INTO `authitem` (`name`, `type`, `description`, `bizrule`, `data`) VALUES
('Equipment.Equipment.*', 1, NULL, NULL, 'N;'),
('Equipment.Equipment.Admin', 0, NULL, NULL, 'N;'),
('Equipment.Equipment.ConnectionTest', 0, NULL, NULL, 'N;'),
('Equipment.Equipment.Create', 0, NULL, NULL, 'N;'),
('Equipment.Equipment.Delete', 0, NULL, NULL, 'N;'),
('Equipment.Equipment.GetEquipment', 0, NULL, NULL, 'N;'),
('Equipment.Equipment.Index', 0, NULL, NULL, 'N;'),
('Equipment.Equipment.Update', 0, NULL, NULL, 'N;'),
('Equipment.Equipment.View', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentcalibration.*', 1, NULL, NULL, 'N;'),
('Equipment.Equipmentcalibration.Admin', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentcalibration.Create', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentcalibration.Delete', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentcalibration.Index', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentcalibration.Update', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentcalibration.View', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentstatus.*', 1, NULL, NULL, 'N;'),
('Equipment.Equipmentstatus.Admin', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentstatus.Create', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentstatus.Delete', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentstatus.Getstatus', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentstatus.Index', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentstatus.Update', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentstatus.View', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.*', 1, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.Addusage', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.Admin', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.Create', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.Delete', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.GetUsage', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.Index', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.Update', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.Updateusage', 0, NULL, NULL, 'N;'),
('Equipment.Equipmentusage.View', 0, NULL, NULL, 'N;');


INSERT INTO `authitemchild` (`parent`, `child`) VALUES
('Lab - System Manager', 'Equipment.Equipment.Admin'),
('Lab - System Manager', 'Equipment.Equipment.ConnectionTest'),
('Lab - System Manager', 'Equipment.Equipment.Create'),
('Lab - System Manager', 'Equipment.Equipment.Delete'),
('Lab - System Manager', 'Equipment.Equipment.GetEquipment'),
('Lab - System Manager', 'Equipment.Equipment.Index'),
('Lab - System Manager', 'Equipment.Equipment.Update'),
('Lab - System Manager', 'Equipment.Equipment.View'),
('Lab - System Manager', 'Equipment.Equipmentcalibration.Admin'),
('Lab - System Manager', 'Equipment.Equipmentcalibration.Create'),
('Lab - System Manager', 'Equipment.Equipmentcalibration.Delete'),
('Lab - System Manager', 'Equipment.Equipmentcalibration.Index'),
('Lab - System Manager', 'Equipment.Equipmentcalibration.Update'),
('Lab - System Manager', 'Equipment.Equipmentcalibration.View'),
('Lab - System Manager', 'Equipment.Equipmentstatus.Admin'),
('Lab - System Manager', 'Equipment.Equipmentstatus.Create'),
('Lab - System Manager', 'Equipment.Equipmentstatus.Delete'),
('Lab - System Manager', 'Equipment.Equipmentstatus.Getstatus'),
('Lab - System Manager', 'Equipment.Equipmentstatus.Index'),
('Lab - System Manager', 'Equipment.Equipmentstatus.Update'),
('Lab - System Manager', 'Equipment.Equipmentstatus.View'),
('Lab - System Manager', 'Equipment.Equipmentusage.Addusage'),
('Lab - System Manager', 'Equipment.Equipmentusage.Admin'),
('Lab - System Manager', 'Equipment.Equipmentusage.Create'),
('Lab - System Manager', 'Equipment.Equipmentusage.Delete'),
('Lab - System Manager', 'Equipment.Equipmentusage.GetUsage'),
('Lab - System Manager', 'Equipment.Equipmentusage.Index'),
('Lab - System Manager', 'Equipment.Equipmentusage.Update'),
('Lab - System Manager', 'Equipment.Equipmentusage.Updateusage'),
('Lab - System Manager', 'Equipment.Equipmentusage.View'),
('Lab - User', 'Equipment.Equipment.Admin'),
('Lab - User', 'Equipment.Equipment.ConnectionTest'),
('Lab - User', 'Equipment.Equipment.Create'),
('Lab - User', 'Equipment.Equipment.Delete'),
('Lab - User', 'Equipment.Equipment.GetEquipment'),
('Lab - User', 'Equipment.Equipment.Index'),
('Lab - User', 'Equipment.Equipment.Update'),
('Lab - User', 'Equipment.Equipment.View'),
('Lab - User', 'Equipment.Equipmentcalibration.Admin'),
('Lab - User', 'Equipment.Equipmentcalibration.Create'),
('Lab - User', 'Equipment.Equipmentcalibration.Delete'),
('Lab - User', 'Equipment.Equipmentcalibration.Index'),
('Lab - User', 'Equipment.Equipmentcalibration.Update'),
('Lab - User', 'Equipment.Equipmentcalibration.View'),
('Lab - User', 'Equipment.Equipmentstatus.Admin'),
('Lab - User', 'Equipment.Equipmentstatus.Create'),
('Lab - User', 'Equipment.Equipmentstatus.Delete'),
('Lab - User', 'Equipment.Equipmentstatus.Getstatus'),
('Lab - User', 'Equipment.Equipmentstatus.Index'),
('Lab - User', 'Equipment.Equipmentstatus.Update'),
('Lab - User', 'Equipment.Equipmentstatus.View'),
('Lab - User', 'Equipment.Equipmentusage.Addusage'),
('Lab - User', 'Equipment.Equipmentusage.Admin'),
('Lab - User', 'Equipment.Equipmentusage.Create'),
('Lab - User', 'Equipment.Equipmentusage.Delete'),
('Lab - User', 'Equipment.Equipmentusage.GetUsage'),
('Lab - User', 'Equipment.Equipmentusage.Index'),
('Lab - User', 'Equipment.Equipmentusage.Update'),
('Lab - User', 'Equipment.Equipmentusage.Updateusage'),
('Lab - User', 'Equipment.Equipmentusage.View');